//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply for a loan.
        /// </summary>
        public static string applyforaloan {
            get {
                return ResourceManager.GetString("applyforaloan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string authorization {
            get {
                return ResourceManager.GetString("authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card number:.
        /// </summary>
        public static string cardnumberlable {
            get {
                return ResourceManager.GetString("cardnumberlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards:.
        /// </summary>
        public static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card type:.
        /// </summary>
        public static string cardtypelable {
            get {
                return ResourceManager.GetString("cardtypelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change mail address.
        /// </summary>
        public static string changemailaddress {
            get {
                return ResourceManager.GetString("changemailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change password.
        /// </summary>
        public static string changepassword {
            get {
                return ResourceManager.GetString("changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change phone number.
        /// </summary>
        public static string changephonenumber {
            get {
                return ResourceManager.GetString("changephonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code:.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Commission.
        /// </summary>
        public static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communal payments.
        /// </summary>
        public static string communalpayments {
            get {
                return ResourceManager.GetString("communalpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment of various utility services 
        ///from a card to a personal account. 
        ///Please make sure you enter your 
        ///account number correctly before 
        ///paying. in order to avoid 
        ///erroneous payment, because in 
        ///case of an erroneous payment 
        ///the bank will not be able to help 
        ///you with the cancellation 
        ///of the payment!.
        /// </summary>
        public static string communalunderlable {
            get {
                return ResourceManager.GetString("communalunderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string createbutton {
            get {
                return ResourceManager.GetString("createbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credit.
        /// </summary>
        public static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credit.
        /// </summary>
        public static string credittypecard {
            get {
                return ResourceManager.GetString("credittypecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loan processing is possible 
        ///only on credit cards! Don&apos;t 
        ///delay your monthly payments 
        ///to avoid penalty fees..
        /// </summary>
        public static string creditunderlable {
            get {
                return ResourceManager.GetString("creditunderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency:.
        /// </summary>
        public static string currencylable {
            get {
                return ResourceManager.GetString("currencylable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current password.
        /// </summary>
        public static string currentpassword {
            get {
                return ResourceManager.GetString("currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CVV-code:.
        /// </summary>
        public static string cvvcode {
            get {
                return ResourceManager.GetString("cvvcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of the loan.
        /// </summary>
        public static string dateoftheloan {
            get {
                return ResourceManager.GetString("dateoftheloan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Debit.
        /// </summary>
        public static string debittypecard {
            get {
                return ResourceManager.GetString("debittypecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t remember login or password.
        /// </summary>
        public static string drlop {
            get {
                return ResourceManager.GetString("drlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expiry date.
        /// </summary>
        public static string expirydate {
            get {
                return ResourceManager.GetString("expirydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fixed annual rate.
        /// </summary>
        public static string fixedannualrate {
            get {
                return ResourceManager.GetString("fixedannualrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From card.
        /// </summary>
        public static string fromcardlable {
            get {
                return ResourceManager.GetString("fromcardlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full name:.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gender:.
        /// </summary>
        public static string genderlable {
            get {
                return ResourceManager.GetString("genderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internet payments.
        /// </summary>
        public static string internetpayments {
            get {
                return ResourceManager.GetString("internetpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment for various internet
        ///services from a card to a personal 
        ///account. Please make sure before 
        ///paying entered the correct number
        ///accounts to avoid erroneous
        ///payment, as in the case
        ///the bank did not make an erroneous
        ///payment can help you cancel
        ///payment!.
        /// </summary>
        public static string internetunderlable {
            get {
                return ResourceManager.GetString("internetunderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string loginbutton {
            get {
                return ResourceManager.GetString("loginbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login:.
        /// </summary>
        public static string loginlable {
            get {
                return ResourceManager.GetString("loginlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail:.
        /// </summary>
        public static string maillable {
            get {
                return ResourceManager.GetString("maillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monthly payment.
        /// </summary>
        public static string monthlypayment {
            get {
                return ResourceManager.GetString("monthlypayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of months.
        /// </summary>
        public static string monthsnumber {
            get {
                return ResourceManager.GetString("monthsnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My credit.
        /// </summary>
        public static string mycredit {
            get {
                return ResourceManager.GetString("mycredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string namelable {
            get {
                return ResourceManager.GetString("namelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New password:.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next payment.
        /// </summary>
        public static string nextpayment {
            get {
                return ResourceManager.GetString("nextpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid.
        /// </summary>
        public static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment system:.
        /// </summary>
        public static string paymentsystemlable {
            get {
                return ResourceManager.GetString("paymentsystemlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal account.
        /// </summary>
        public static string personalaccount {
            get {
                return ResourceManager.GetString("personalaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal data.
        /// </summary>
        public static string personaldata {
            get {
                return ResourceManager.GetString("personaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal data changes.
        /// </summary>
        public static string personaldatachanges {
            get {
                return ResourceManager.GetString("personaldatachanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone:.
        /// </summary>
        public static string phonelable {
            get {
                return ResourceManager.GetString("phonelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replenishment of Belarusian numbers only 
        ///(80 or +375).
        /// </summary>
        public static string phoneunderlable {
            get {
                return ResourceManager.GetString("phoneunderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN-code.
        /// </summary>
        public static string pincodelable {
            get {
                return ResourceManager.GetString("pincodelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipient&apos;s card.
        /// </summary>
        public static string recipientscard {
            get {
                return ResourceManager.GetString("recipientscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recovery.
        /// </summary>
        public static string recovery {
            get {
                return ResourceManager.GetString("recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repit:.
        /// </summary>
        public static string repitlable {
            get {
                return ResourceManager.GetString("repitlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replenishment only to Belarusian numbers.
        /// </summary>
        public static string replenishmentonlytobelarusiannumbers {
            get {
                return ResourceManager.GetString("replenishmentonlytobelarusiannumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russion.
        /// </summary>
        public static string russion {
            get {
                return ResourceManager.GetString("russion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign out.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum.
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surname:.
        /// </summary>
        public static string surnamelable {
            get {
                return ResourceManager.GetString("surnamelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer to VISA or MasterCard 
        ///without commission!.
        /// </summary>
        public static string tocardunderlable {
            get {
                return ResourceManager.GetString("tocardunderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To payment.
        /// </summary>
        public static string topayment {
            get {
                return ResourceManager.GetString("topayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top up mobile.
        /// </summary>
        public static string topupmobile {
            get {
                return ResourceManager.GetString("topupmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top up your account.
        /// </summary>
        public static string topupyouraccount {
            get {
                return ResourceManager.GetString("topupyouraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transaction type.
        /// </summary>
        public static string transactiontype {
            get {
                return ResourceManager.GetString("transactiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer.
        /// </summary>
        public static string transferbutton {
            get {
                return ResourceManager.GetString("transferbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer to the card.
        /// </summary>
        public static string transfertothecard {
            get {
                return ResourceManager.GetString("transfertothecard", resourceCulture);
            }
        }
    }
}
