//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string authorization {
            get {
                return ResourceManager.GetString("authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card number:.
        /// </summary>
        public static string cardnumberlable {
            get {
                return ResourceManager.GetString("cardnumberlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards:.
        /// </summary>
        public static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card type:.
        /// </summary>
        public static string cardtypelable {
            get {
                return ResourceManager.GetString("cardtypelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code:.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string createbutton {
            get {
                return ResourceManager.GetString("createbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credit.
        /// </summary>
        public static string credittypecard {
            get {
                return ResourceManager.GetString("credittypecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency:.
        /// </summary>
        public static string currencylable {
            get {
                return ResourceManager.GetString("currencylable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CVV-code:.
        /// </summary>
        public static string cvvcode {
            get {
                return ResourceManager.GetString("cvvcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Debit.
        /// </summary>
        public static string debittypecard {
            get {
                return ResourceManager.GetString("debittypecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t remember login or password.
        /// </summary>
        public static string drlop {
            get {
                return ResourceManager.GetString("drlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expiry date.
        /// </summary>
        public static string expirydate {
            get {
                return ResourceManager.GetString("expirydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From card.
        /// </summary>
        public static string fromcardlable {
            get {
                return ResourceManager.GetString("fromcardlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gender:.
        /// </summary>
        public static string genderlable {
            get {
                return ResourceManager.GetString("genderlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string loginbutton {
            get {
                return ResourceManager.GetString("loginbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login:.
        /// </summary>
        public static string loginlable {
            get {
                return ResourceManager.GetString("loginlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail:.
        /// </summary>
        public static string maillable {
            get {
                return ResourceManager.GetString("maillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string namelable {
            get {
                return ResourceManager.GetString("namelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment system:.
        /// </summary>
        public static string paymentsystemlable {
            get {
                return ResourceManager.GetString("paymentsystemlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone:.
        /// </summary>
        public static string phonelable {
            get {
                return ResourceManager.GetString("phonelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN-code.
        /// </summary>
        public static string pincodelable {
            get {
                return ResourceManager.GetString("pincodelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipient&apos;s card.
        /// </summary>
        public static string recipientscard {
            get {
                return ResourceManager.GetString("recipientscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recovery.
        /// </summary>
        public static string recovery {
            get {
                return ResourceManager.GetString("recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repit:.
        /// </summary>
        public static string repitlable {
            get {
                return ResourceManager.GetString("repitlable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum.
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surname:.
        /// </summary>
        public static string surnamelable {
            get {
                return ResourceManager.GetString("surnamelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer.
        /// </summary>
        public static string transferbutton {
            get {
                return ResourceManager.GetString("transferbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer to the card.
        /// </summary>
        public static string transfertothecard {
            get {
                return ResourceManager.GetString("transfertothecard", resourceCulture);
            }
        }
    }
}
